name: docker.yml
on:
  push:
    branches:
      - master-voice

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout chat-service
        uses: actions/checkout@v4

      - name: Checkout core-lib
        uses: actions/checkout@v4
        with:
          repository: oprosto/core-lib
          path: ./libs/core-lib
          token: ${{ secrets.LIBS_ACCESS_TOKEN }}

      - name: Checkout security-lib
        uses: actions/checkout@v4
        with:
          repository: oprosto/security-lib
          path: ./libs/security-lib
          token: ${{ secrets.LIBS_ACCESS_TOKEN }}

      - name: Login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/voice-chat-service:latest





